# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-07 03:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201207_0340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='gambar',
        ),
    ]
