# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-07 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_post_gambar'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='gambar',
            field=models.ImageField(default='default.jpg', upload_to='blog_img'),
        ),
    ]
