# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-04 07:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0002_auto_20201204_0657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profil',
            old_name='image',
            new_name='gambar',
        ),
        migrations.RenameField(
            model_name='profil',
            old_name='user',
            new_name='pengguna',
        ),
    ]
