# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-05 05:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0004_auto_20201204_0710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profil',
            old_name='Hp',
            new_name='hp',
        ),
    ]
