# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-10 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0012_auto_20201207_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='nama_lengkap',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
